tenancy:
    name:
    ocid:
    core-compartments:
        - landing-zone-compartment:
            name: 
            description: 
            parent: "<Root-Compartment-OCID>"
        - tenancy-admin-compartment:
            name: 
            description: 
            parent: "<Root-Compartment-OCID>"
    user-defined-compartments:
        - compartment A:
        - compartment B:
        - compartment C:
        - compartment D:

    core-groups:
        - network-admins:
            name:
            description:
        - backup-admins:
            name:
            description:
        - database-admins:
            name:
            description:
        - os-admins:
            name:
            description:
        - net-sec-admins:
            name:
            description:
        - auditors:
            name:
            description:
    name: landing-zone-network-policy
    description: "A Network Policy to Allow all Network Admins to Manage all network resources except Firewall & Security & Public IPs within the Tenancy"
    statements:
        - "Allow group network-admins to manage repos in tenancy"
        - "Allow group splunk-export-users to read audit-events in tenancy"
        - "Allow group splunk-export-users to read tenancies in tenancy"
        - "Allow group splunk-export-users to read compartments in tenancy"
        - "Allow service FaaS to read repos in tenancy"
        - "Allow group splunk-export-users to use cloud-shell in tenancy"
        - "Allow group splunk-export-users to use ons-family in tenancy"
        - "Allow group splunk-export-users to use streams in tenancy"
        - "Allow group splunk-export-dg to read audit-events in tenancy"
        - "Allow group splunk-export-dg to read tenancies in tenancy"
        - "Allow group splunk-export-dg to read compartments in tenancy"