core-compartments:
    - landing-zone-compartment:
        name: 
        description: 
        parent: "<Root-Compartment-OCID>"
    - tenancy-admin-compartment:
        name: 
        description: 
        parent: "<Root-Compartment-OCID>"
        
core-groups:
    - network-admins:
        name:
        description:
    - storage-admins:
        name:
        description:
    - database-admins:
        name:
        description:
    - os-admins:
        name:
        description:
    - net-sec-admins:
        name:
        description:
    - auditors:
        name:
        description:


